# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JSONAPP' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 source 'https://github.com/CocoaPods/Specs.git'
pod "Alamofire"
  # Pods for JSONAPP

  target 'JSONAPPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JSONAPPUITests' do
    # Pods for testing
  end

end
